banocean/ifv

manifest.json

- Added *://uczen.eduvulcan.pl/* and *://wiadomosci.eduvulcan.pl/* to included hosts

Add subdomains of `eduvulcan.pl` to `host_permissions` (manifest.json)

---

apply.js
patches/alignDetailedGradesButton.css

After changes:
Before changes:

Align button for opening detailed list of grades

---

apply.js
patches/hideHelpOnDashboard.css

Hide help block on dashboard

---

apply.js
patches/attendance/styles.css
patches/attendance/tabs.js

[Screencast from 2024-08-29 18-56-30.webm](https://github.com/user-attachments/assets/61af15d1-3f00-4dd0-8a79-699d1726371f)

Add tabs for switching between stats and timetable on attendance page

---

patches/cleanUpEduVulcanHome.css

(fix): header alignment on `eduvulcan.pl`

---

patches/pwa.js

PWA support on `dziennik-uczen.vulcan.net.pl`

---

apply.js

Reverts banocean/ifv#21
It breaks Firefox support due URLPattern usage (reintroduction of #23 issues too)

Revert "(fix): config isn't preserved after closing browser"

---

apply.js
execute.js
manifest.json
patches.json
patches/attendance/tabs.js
patches/displayFullName.js
patches/fixResizing.js
patches/newMobileNavbar/highlights.js
patches/newMobileNavbar/index.js
patches/pwa.js
patches/redirectToBoard/script.js
patches/redirectToEVLogin.js

Fixes https://github.com/banocean/ifv/issues/46

Switch to content scripts

---

README.md

(fix): typo in README.md

---

patches/hideFooter.css
patches/newMobileNavbar/styles.css

(fix): modal footer not present on attendance and messages pages

---

patches/moveUserOptionsToHeader/script.js

(fix): wait for links in user options to render

---

popup/index.html
popup/main.js
popup/style.css

(fix): patches not rendering in pop-up before opening vulcan

---

manifest.json
popup/index.html

Release 0.3

---

patches.json
patches/hideEmptyExamResults.css

Hide exam results when data is not present

---

popup/main.js

Dynamiczna zmiana wyświetlanych patchów z każdym wpisanym znakiem
https://github.com/user-attachments/assets/0bddf08f-c69f-42f6-9b35-fe721326c482

Refactor filter functionality and improve user experience

---

patches.json

Update and add missing descriptions to patches

---

patches/moveUserOptionsToHeader/styles.css

(fix): text overflow in user modal

---

patches.json
patches/highlightToday.css
patches/newMobileNavbar/styles.css

Hilight current day in calendars

---

patches/arrows.css
patches/fixGoingBack.js

(fix): Go backward icons in modals and history api patch

---

patches/apis/aside.js

fix otwierania się bocznego menu po wejściu do wiadomości

(fix): update selector for the aside close button

---

apply.js
patches.json
patches/fixResizing.js
patches/hideSubjectsWithNoGrades/finalGrades.js
patches/messagesButton.js
patches/moveUserOptionsToHeader/script.js
patches/newMobileNavbar/highlights.js
patches/newMobileNavbar/index.js
popup/index.html
popup/main.js
popup/style.css

This pull request introduces device-specific patch injection and refactors the codebase for better readability and maintainability. The changes include adding a new property to specify device types, updating the logic to inject patches based on the device type, and making several code style improvements.
* [`apply.js`](diffhunk://#diff-6e3c1529d6423fbe01bd1515f9f37c26caf0da3b45b79602dcb7a9a8ef61fc18R8): Added a new property `devices` to specify device type for patches and updated the logic to inject patches based on the device type. [[1]](diffhunk://#diff-6e3c1529d6423fbe01bd1515f9f37c26caf0da3b45b79602dcb7a9a8ef61fc18R8) [[2]](diffhunk://#diff-6e3c1529d6423fbe01bd1515f9f37c26caf0da3b45b79602dcb7a9a8ef61fc18R31-R100)
* [`patches.json`](diffhunk://#diff-fa73aa2aea0f1b6bf027000008e8557578170 …

displaying patches for specific devices and prettier popup

---

patches/cleanUpEduVulcanHome.css

hide articles in eduvulcan home

---

patches/darkTheme/main.css

General fixes for dark theme.
- Fixes new mobile Table
- Fixed calendar icons in commit [0dccc2a](https://github.com/banocean/ifv/pull/124/commits/0dccc2a623f8e46a7d37a218630fc500ad13278f)

More dark theme fixes
